### ISSUE TITLE
Update to newest version of railties

### ISSUE THREAD

**Issue by moonglum** [nragaz/tipsy-rails#1]
Currently the gem depends on version 3.0.0 of railties. Current Version is 3.2.0. Would you update it to the newest version?

(Would do it, but there are no tests and I don't want to break it!)

**Comment by nragaz** [comment]
Because of the way the dependency is written ("~> 3.0"), it should work with 3.1, 3.2, etc. - just not 4.x.

Are you running into a specific issue?

**Comment by moonglum** [comment]
I'm sorry! Just saw that this issue has nothing to do with tipsy-rails  but the non-existence of rails 3.2.0.beta on RubyGems.org even if referenced by the newest sass-rails. It just so happened that your gem was the first in the list that showed that conflict!

Status: Rejected – No bug!
