### ISSUE TITLE
tipsy-rails should depend on sass-rails

### ISSUE THREAD

**Issue by madx** [nragaz/tipsy-rails#2]
As the CSS file is preprocessed by SCSS, there should be a dependency on `sass-rails`.

Applications not relying on `sass-rails` may encounter this error when booting :

```
no such file to load -- sass
  (in /home/madx/.rbenv/versions/1.8.7-p358-glibcfix/lib/ruby/gems/1.8/gems/tipsy-rails-1.0.2/vendor/assets/stylesheets/tipsy.css.scss)
```

**Comment by nragaz** [comment]
Thanks!
